name: bhalala
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  sizer: ^2.0.15
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0
  fluttertoast: ^8.2.1
  dart_quote: ^0.0.2
  intl: ^0.18.0
  image_picker: ^0.8.7
  http: ^0.13.5
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.0.20
  email_validator: ^2.1.17
  loader_overlay: ^2.1.0
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/images/
   - assets/Icons/

