// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATCabCgzVVS5qsrDptygw0sPnoqsgk-eI',
    appId: '1:334859371080:web:7263e1294604bf0e320e7d',
    messagingSenderId: '334859371080',
    projectId: 'bhalalaparivar-b564d',
    authDomain: 'bhalalaparivar-b564d.firebaseapp.com',
    storageBucket: 'bhalalaparivar-b564d.appspot.com',
    measurementId: 'G-5EVXWE580K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1sBOQf_qxTeNxx1DtWY_PACyjunhAZcQ',
    appId: '1:334859371080:android:9bc070069079d445320e7d',
    messagingSenderId: '334859371080',
    projectId: 'bhalalaparivar-b564d',
    storageBucket: 'bhalalaparivar-b564d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk5Qbr6ruwq0qYkLD9ZHjay88T81kF8Q4',
    appId: '1:334859371080:ios:94abf5bd1f364e94320e7d',
    messagingSenderId: '334859371080',
    projectId: 'bhalalaparivar-b564d',
    storageBucket: 'bhalalaparivar-b564d.appspot.com',
    iosClientId: '334859371080-qd7l91skhu0q7b2ha7v3oibhovkjdd8h.apps.googleusercontent.com',
    iosBundleId: 'com.argon.bhalala.parivar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk5Qbr6ruwq0qYkLD9ZHjay88T81kF8Q4',
    appId: '1:334859371080:ios:94abf5bd1f364e94320e7d',
    messagingSenderId: '334859371080',
    projectId: 'bhalalaparivar-b564d',
    storageBucket: 'bhalalaparivar-b564d.appspot.com',
    iosClientId: '334859371080-qd7l91skhu0q7b2ha7v3oibhovkjdd8h.apps.googleusercontent.com',
    iosBundleId: 'com.argon.bhalala.parivar',
  );
}
