// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJXgJ6ZQ5GjFftmyJxYQVJja-nznPBlvQ',
    appId: '1:325859453673:web:c3d808798e59d51e435e78',
    messagingSenderId: '325859453673',
    projectId: 'bhalalaparivar-a0ce9',
    authDomain: 'bhalalaparivar-a0ce9.firebaseapp.com',
    storageBucket: 'bhalalaparivar-a0ce9.appspot.com',
    measurementId: 'G-CWTGYN9750',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeSW2S9huUmKksfLMyjg90iL7r_N1HNDg',
    appId: '1:325859453673:android:e2ea87783fa7f714435e78',
    messagingSenderId: '325859453673',
    projectId: 'bhalalaparivar-a0ce9',
    storageBucket: 'bhalalaparivar-a0ce9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr_3bymal06GbtKnegf4QQlnxCXCB2jdI',
    appId: '1:325859453673:ios:ae5f1099e0d07478435e78',
    messagingSenderId: '325859453673',
    projectId: 'bhalalaparivar-a0ce9',
    storageBucket: 'bhalalaparivar-a0ce9.appspot.com',
    iosClientId: '325859453673-kespmka89qbtafqgji99qtlg4gvv9hd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhalala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr_3bymal06GbtKnegf4QQlnxCXCB2jdI',
    appId: '1:325859453673:ios:ae5f1099e0d07478435e78',
    messagingSenderId: '325859453673',
    projectId: 'bhalalaparivar-a0ce9',
    storageBucket: 'bhalalaparivar-a0ce9.appspot.com',
    iosClientId: '325859453673-kespmka89qbtafqgji99qtlg4gvv9hd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhalala',
  );
}
